### PR TITLE
1) Connection error printout; 2) Fixed typos at terminated characters

### PR DESCRIPTION
**Pull request by ErlingSigurdson**

### CODE REVIEW

**Comment by ErlingSigurdson** [comment]
Hi there, I'm just a random guy who spotted some typos.

**Comment by Zyrem** [comment]
Thanks for your contribution

**Comment by ErlingSigurdson** [comment]
What about a merge? :)

**Comment by ErlingSigurdson** [comment]
Just noticed it's a really old repo, lol.

**Pull request merged**
